import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { Analytics } from '@vercel/analytics/next';



export const metadata: Metadata = {
  title: 'Hamtec Project',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Analytics />
        <Footer />
          
      </body>
    </html>
  );
}