import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { Analytics } from "@vercel/analytics/next";
import { Providers } from "./providers";
import { ThemeToggle } from "./components/ThemeToggle";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Hamtec Project",
  description: "Generated by Next.js",
  keywords: ["construction", "landscaping", "cleaning", "project management"],
  authors: [{ name: "Hamtec" }],
  openGraph: {
    title: "Hamtec Project",
    description: "Explore our diverse range of successful projects.",
    url: "https://hamtec-project.vercel.app/",
    siteName: "Hamtec",
    images: [
      { url: "/og-image.jpg", width: 1200, height: 630, alt: "Hamtec Project" },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-TYYL7GZPY1`}
        />
        <Script
          id="ga-setup"
          strategy="afterInteractive"
        >
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-TYYL7GZPY1');
          `}
        </Script>
      </head>
      <body>
        {/* <Providers> */}
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Analytics />
          </div>

          {/* FLOATING THEME TOGGLE */}
          {/* <ThemeToggle /> */}
        {/* </Providers> */}
      </body>
    </html>
  );
}
