import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { Analytics } from "@vercel/analytics/next";
import { Providers } from "./providers";
import { ThemeToggle } from "./components/ThemeToggle";

export const metadata: Metadata = {
  title: "Hamtec Project",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Analytics />
          </div>

          {/* FLOATING THEME TOGGLE */}
          <ThemeToggle />
        </Providers>
      </body>
    </html>
  );
}
